name: Notebook_ModernGMT
channels:
    - conda-forge/label/dev
    - conda-forge
    - defaults
dependencies:
    - python=3.6
    - pip
    - gmt=6.0.0a17
    - numpy
    - pandas
    - matplotlib
    - jupyter